name: LoupGarou
version: 1.1.0
description: Permet de jouer au jeu du loup garou
main: fr.timothefcn.mc.loupgarou.MainLg
depend: [ProtocolLib]
api-version: 1.13
commands:
  admin:
  create:
  join:
  leave:
    aliases: exit